# This is a basic workflow to help you get started with Actions

name: Server Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy on Self-Hosted Runner
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/tpqnurulfajar.online
    steps:
      # Runs a single command using the runners shell
      - name: Running git pull
        run: |
          echo ${{ secrets.SERVER_PASSWORD }} | sudo -S git pull -f
          sudo git reset --hard
      - name: Setting up file permissions
        run: |
          echo ${{ secrets.SERVER_PASSWORD }} | sudo -S chown -R www-data:www-data . 
          sudo find . -type f -exec chmod 644 {} \; 
          sudo find . -type d -exec chmod 755 {} \; 
          sudo chgrp -R www-data storage bootstrap/cache 
          sudo chmod -R ug+rwx storage bootstrap/cache 
      - name: Checking Laravel migration changes
        run: |
          count=$(git show | grep -q migrations) 
          exit=$? 
          if [[ $exit == 1 ]]; then php artisan migrate:fresh --seed; fi || true
