# This is a basic workflow to help you get started with Actions

name: Server Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run github pull on server
          # You may pin to the exact commit or the version.
        # uses: garygrossgarten/github-action-ssh@d2ce399984eed21f8cf2a26d28ba309e1ed52fc5
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          # Command to execute on the remote server.
          command: sudo cat test
          # Hostname or IP address of the server.
          host: ${{ secrets.SERVER_HOST }}
          # Username for authentication.
          username: ${{ secrets.SERVER_USERNAME }}
          # Port number of the server.
          port: 22
          # Password for password-based user authentication.
          password: ${{ secrets.SERVER_PASSWORD }}
